#!/usr/bin/env bash
# Build an installable native package of Agent Kate from your *current* source
# tree (uncommitted edits included), with Go dependencies vendored so the
# package build needs no network.
#
#   scripts/package.sh            # build a distro package (Arch: .pkg.tar.zst)
#   scripts/package.sh --source   # only the vendored source tarball
#
# Output lands in ./dist/. On Arch the package can be installed/upgraded with
# scripts/install.sh (pacman -U). On other distros this prints the matching
# recipe from packaging/README.md.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SOURCE_ONLY=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source) SOURCE_ONLY=1 ;;
        -h|--help) grep '^#' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//; 1d'; exit 0 ;;
        *) die "unknown option: $1 (try --help)" ;;
    esac
    shift
done

cd "$ROOT"
require_cmd git
require_cmd go "Needed to vendor Go modules. Arch: pacman -S go"

VERSION="$(project_version)"
[[ -n "$VERSION" ]] || die "could not detect version from CMakeLists.txt"
NAME="agentkate-${VERSION}"
DIST="${ROOT}/dist"
STAGE="${DIST}/${NAME}"
TARBALL="${DIST}/${NAME}.tar.gz"

# --- 1. assemble a source tree from the working copy ------------------------
step "Assembling source tree ($NAME)"
mkdir -p "$DIST"
rm -rf "$STAGE"
mkdir -p "$STAGE"

# Copy git-tracked files plus untracked-but-not-ignored files, so the package
# reflects exactly what you have checked out (honours .gitignore). Skip the
# build/ and dist/ trees so prior outputs never get folded back in.
{ git ls-files -z; git ls-files --others --exclude-standard -z; } \
    | sort -zu \
    | while IFS= read -r -d '' f; do
        case "$f" in dist/*|build/*) continue ;; esac
        mkdir -p "${STAGE}/$(dirname "$f")"
        cp -a "$f" "${STAGE}/$f"
    done
ok "copied $(find "$STAGE" -type f | wc -l) files"

step "Vendoring Go modules (offline-ready)"
( cd "${STAGE}/core" && go mod vendor )
ok "vendored into ${NAME}/core/vendor"

step "Writing source tarball"
tar -C "$DIST" -czf "$TARBALL" "$NAME"
ok "dist/${NAME}.tar.gz ($(du -h "$TARBALL" | cut -f1))"

if [[ "$SOURCE_ONLY" == 1 ]]; then
    rm -rf "$STAGE"
    step "Done (source only)"
    info "Use this tarball with the RPM/DEB recipes in packaging/README.md."
    exit 0
fi

FAMILY="$(distro_family)"
if [[ "$FAMILY" != "arch" ]]; then
    rm -rf "$STAGE"
    warn "Automated package build is implemented for Arch-family systems only."
    info "Detected distro family: ${C_BOLD}${FAMILY}${C_RESET}"
    info "Your source tarball is ready at ${C_BOLD}${TARBALL}${C_RESET}."
    info "Follow the ${FAMILY}/generic recipe in ${C_BOLD}packaging/README.md${C_RESET} to build a native package."
    exit 0
fi

# --- 2. build an Arch package from the local tarball ------------------------
require_cmd makepkg "Arch: part of the 'pacman' / base-devel toolchain."

step "Generating PKGBUILD (local source)"
# Based on packaging/arch/PKGBUILD, but pointed at the local tarball with deps
# already vendored, so prepare() does no network access.
cat > "${DIST}/PKGBUILD" <<PKGBUILD
# Generated by scripts/package.sh — builds from the local working tree.
# Maintainer: Mike Pengelly <mike@leadrix.io>
pkgname=agentkate
pkgver=${VERSION}
pkgrel=1
pkgdesc="Native KDE multi-agent coding arena built on the Kate editor engine"
arch=('x86_64' 'aarch64')
url="https://github.com/mpengelly/AgentKate"
license=('LGPL-2.0-or-later')
depends=(
    'qt6-base' 'kcoreaddons' 'kconfig' 'kconfigwidgets' 'ki18n'
    'kxmlgui' 'kparts' 'kwidgetsaddons' 'ktexteditor'
    'syntax-highlighting' 'konsole'
)
makedepends=('cmake' 'ninja' 'extra-cmake-modules' 'go' 'git')
optdepends=(
    'git: source control integration'
    'okular: view PDF/ePub/DjVu/comic-book and ODF/Office documents in editor tabs'
    'calligra: render Word/Excel/PowerPoint and ODF documents via Okular'
    'ark: inspect zip/tar archives in editor tabs'
)
source=("\$pkgname-\$pkgver.tar.gz")
sha256sums=('SKIP')

# Go deps are already vendored by scripts/package.sh — no prepare() needed.

build() {
    cd "${NAME}"
    export GOFLAGS="-mod=vendor -trimpath"
    export GOPROXY=off
    cmake -S . -B build -G Ninja \\
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \\
        -DCMAKE_INSTALL_PREFIX=/usr \\
        -DAGENTKATE_VERSION=${VERSION}
    cmake --build build
}

package() {
    cd "${NAME}"
    DESTDIR="\$pkgdir" cmake --install build
    install -Dm644 LICENSES/LGPL-2.0-or-later.txt \\
        "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
}
PKGBUILD
ok "dist/PKGBUILD"

step "Building package with makepkg"
info "This compiles a clean RelWithDebInfo build; it may take a minute."
( cd "$DIST" && makepkg -f --noconfirm )

# Tidy makepkg's scratch dirs and the source tree so dist/ holds only outputs.
rm -rf "$STAGE" "${DIST}/pkg" "${DIST}/src" "${DIST}/PKGBUILD"
PKG="$(ls -t "${DIST}"/agentkate-"${VERSION}"-*.pkg.tar.* 2>/dev/null | head -n1 || true)"
[[ -n "$PKG" ]] || die "makepkg finished but no package file was found in dist/"

step "Done"
ok "Package: ${C_BOLD}${PKG}${C_RESET}"
info "Install or upgrade it with ${C_BOLD}scripts/install.sh${C_RESET}."
